# Generated by Django 3.2.6 on 2021-08-30 01:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210829_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Contenido'),
        ),
    ]
